# Generated by Django 4.2.2 on 2023-07-02 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='parent_number',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='info',
            name='whatsapp',
            field=models.CharField(max_length=11),
        ),
    ]
