# Generated by Django 4.1.5 on 2023-07-07 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_info_parent_number_alter_info_whatsapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='center',
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='info',
            name='academic_year',
            field=models.CharField(max_length=50),
        ),
    ]
